#!/usr/bin/env python3
"""Portable bounded bioinformatics previews and non-destructive archives."""
import argparse
import contextlib
import gzip
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import signal
import subprocess
import sys
import tarfile
import tempfile
import zipfile

VERSION = '0.1.0'
LIMIT = 1024 * 1024
INDEX = ('.bai', '.csi', '.tbi', '.gzi', '.0123', '.bwt.2bit.64', '.pac', '.bwt', '.sa')
SPECIAL = ('.bw', '.bigwig', '.bb', '.bigbed', '.h5', '.hdf5', '.h5ad', '.rds', '.rdata', '.rda')
ARCHIVES = ('.tar', '.tar.gz', '.tgz', '.tar.bz2', '.tbz2', '.tar.xz', '.txz', '.tar.zst', '.tzst')

class Error(Exception):
    pass


def tool(name):
    # Site-local configuration is generated by the installer, never distributed.
    config = Path(__file__).resolve().parent / 'runtime.json'
    mapping = json.loads(config.read_text()) if config.exists() else {}
    result = mapping.get(name) or shutil.which(name)
    if not result or not os.access(result, os.X_OK):
        raise Error('Missing dependency: ' + name + '; install it in a personal environment')
    return result


def regular(value):
    p = Path(value).absolute()
    if not p.is_file():
        raise Error('Not a readable regular file: ' + str(p))
    return p


def compression(path):
    with path.open('rb') as f:
        magic = f.read(6)
    if magic.startswith(b'\x1f\x8b'): return 'gzip'
    if magic.startswith(b'\x28\xb5\x2f\xfd'): return 'zstd'
    if magic.startswith(b'BZh'): return 'bzip2'
    if magic.startswith(b'\xfd7zXZ\x00'): return 'xz'
    return None


class Reader:
    """A bounded consumer; intentional truncation cancels the producer, errors do not."""
    def __init__(self, path, command=None, env=None):
        self.command = command
        if command is None:
            c = compression(path)
            if c:
                command = [tool(c), '-dc', str(path)]
        self.proc = None
        self.truncated = False
        self.error = tempfile.TemporaryFile()
        if command:
            self.proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=self.error, env=env)
            self.stream = self.proc.stdout
        else:
            self.stream = path.open('rb')

    def close(self, cancel=False):
        self.stream.close()
        code = 0
        if self.proc:
            if cancel and self.proc.poll() is None:
                self.proc.terminate()
            try:
                code = self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill(); code = self.proc.wait()
        self.error.seek(0)
        message = self.error.read(8192).decode('utf-8', 'replace').strip()
        self.error.close()
        if code and not cancel:
            raise Error(message or 'Reader failed with exit code ' + str(code))


@contextlib.contextmanager
def reader(path, command=None, env=None):
    r = Reader(path, command, env)
    try:
        yield r
    except BaseException:
        r.close(cancel=True)
        raise
    else:
        r.close(cancel=r.truncated)


def safe_text(data):
    # Escape terminal controls while preserving tabs, newlines and UTF-8.
    text = data.decode('utf-8', 'replace')
    return ''.join(c if c in '\n\t' or (ord(c) >= 32 and not 127 <= ord(c) < 160) else '\\x%02x' % ord(c) for c in text)


def preview_stream(r, lines, byte_limit):
    output = bytearray()
    for _ in range(lines):
        remaining = byte_limit - len(output)
        if remaining <= 0:
            r.truncated = True; break
        chunk = r.stream.readline(remaining)
        if not chunk: break
        output.extend(chunk)
    else:
        r.truncated = True
    if len(output) >= byte_limit: r.truncated = True
    if b'\x00' in output:
        return 'Metadata only: binary content detected; use a format-specific reader\n'
    return safe_text(bytes(output))


def display(text, no_pager):
    if sys.stdout.isatty() and not no_pager and shutil.which('less'):
        env = os.environ.copy()
        env['LESSSECURE'] = '1'
        p = subprocess.Popen([shutil.which('less'), '-F', '-S', '-X'], stdin=subprocess.PIPE, env=env)
        try:
            p.communicate(text.encode('utf-8'))
        except BrokenPipeError:
            p.wait()
    else:
        sys.stdout.write(text)


def peek(args):
    path = regular(args.input)
    name = path.name.lower()
    if name.endswith(INDEX + SPECIAL):
        print('Metadata only: %s\nSize: %d bytes\nClass: %s' % (path.name, path.stat().st_size, 'binary index' if name.endswith(INDEX) else 'specialized binary format'))
        return
    if name.endswith('.zip'):
        with zipfile.ZipFile(path) as z:
            result = bytearray()
            truncated = False
            for i, member in enumerate(z.infolist()):
                row = ('%d\t%s\n' % (member.file_size, member.filename)).encode()
                if i >= args.lines or len(result) + len(row) > args.max_bytes:
                    truncated = True; break
                result.extend(row)
        display(safe_text(result), args.no_pager)
    elif name.endswith(ARCHIVES):
        result = bytearray(); truncated = False
        with reader(path) as r:
            with tarfile.open(fileobj=r.stream, mode='r|') as archive:
                for i, member in enumerate(archive):
                    row = ('%d\t%s\n' % (member.size, member.name)).encode()
                    if i >= args.lines or len(result) + len(row) > args.max_bytes:
                        r.truncated = truncated = True; break
                    result.extend(row)
            # tar end markers can precede a compressed checksum; drain to verify it.
            if not r.truncated:
                while r.stream.read(65536): pass
        display(safe_text(result), args.no_pager)
    else:
        command = None
        env = None
        if name.endswith(('.bam', '.cram')):
            command = [tool('samtools'), 'view', '--no-PG', '-H' if args.header else '-h']
            if name.endswith('.cram') and not args.header:
                if not args.reference:
                    raise Error('CRAM record preview requires --reference <local.fa>; use --header for header only')
                reference = regular(args.reference)
                if not Path(str(reference) + '.fai').is_file():
                    raise Error('Reference .fai must already exist; peek never creates an index')
                command += ['-T', str(reference)]
                env = os.environ.copy(); env['REF_PATH'] = str(reference.parent); env['REF_CACHE'] = ''
            command.append(str(path))
        elif name.endswith('.bcf'):
            command = [tool('bcftools'), 'view', '--no-version', '-h' if args.header else '-Ov', str(path)]
        elif args.header:
            raise Error('--header is supported for BAM, CRAM and BCF; use -n for text formats')
        with reader(path, command, env) as r:
            text = preview_stream(r, args.lines, args.max_bytes)
            truncated = r.truncated
        display(text, args.no_pager)
    if truncated:
        print('peek: preview limit reached; this is not a complete integrity check', file=sys.stderr)


def compressor(fmt, threads, level):
    if fmt == 'zstd': return [tool('zstd'), '-q', '-c', '-T' + str(threads), '-' + str(level)]
    if fmt == 'gzip': return [tool('gzip'), '-c', '-n', '-' + str(min(level, 9))]
    return [tool('bgzip'), '-c', '-@', str(threads), '-l', str(min(level, 9))]


def publish(partial, target):
    # Atomic no-clobber publication on the same filesystem.
    os.link(str(partial), str(target))
    partial.unlink()


def pack(args):
    source = Path(args.input).absolute()
    if source.is_symlink() or not (source.is_file() or source.is_dir()):
        raise Error('Input must be a regular file or directory, not a top-level symbolic link')
    is_dir = source.is_dir()
    if is_dir and args.format != 'zstd':
        raise Error('Directory archives use zstd (.tar.zst) in this version')
    suffix = '.tar.zst' if is_dir else '.zst' if args.format == 'zstd' else '.gz'
    target = Path(args.output).absolute() if args.output else source.with_name(source.name + suffix)
    if target.exists() or target.is_symlink(): raise Error('Output already exists: ' + str(target))
    if not target.parent.is_dir(): raise Error('Output parent directory does not exist')
    if is_dir and (target.parent.resolve() == source.resolve() or source.resolve() in target.parent.resolve().parents):
        raise Error('Archive output must be outside the source directory')
    if not is_dir and source.name.lower().endswith(('.gz', '.zst', '.xz', '.bz2', '.bam', '.cram', '.bcf', '.zip')):
        print('packz: input is already compressed; additional compression may save little space', file=sys.stderr)
    command = compressor(args.format, args.threads, args.level)
    fd, name = tempfile.mkstemp(prefix=target.name + '.partial-', dir=str(target.parent))
    partial = Path(name)
    try:
        with os.fdopen(fd, 'wb') as out:
            if is_dir:
                env = os.environ.copy(); env['COPYFILE_DISABLE'] = '1'
                tar = subprocess.Popen([tool('tar'), '-cf', '-', '-C', str(source.parent), '--', source.name], stdout=subprocess.PIPE, env=env)
                try:
                    result = subprocess.run(command, stdin=tar.stdout, stdout=out)
                    tar.stdout.close()
                    tarcode = tar.wait()
                finally:
                    if tar.poll() is None: tar.terminate(); tar.wait()
                if result.returncode or tarcode: raise Error('Archive/compressor failed; partial output retained')
            else:
                before = source.stat()
                with source.open('rb') as inp:
                    result = subprocess.run(command, stdin=inp, stdout=out)
                after = source.stat()
                if result.returncode: raise Error('Compressor failed; partial output retained')
                if (before.st_size, before.st_mtime_ns, before.st_ino) != (after.st_size, after.st_mtime_ns, after.st_ino):
                    raise Error('Source changed during compression; partial output retained')
            out.flush(); os.fsync(out.fileno())
        check = [tool('zstd' if args.format == 'zstd' else 'gzip'), '-t', str(partial)]
        if subprocess.run(check).returncode: raise Error('Compressed stream integrity test failed')
        publish(partial, target)
    except BaseException:
        print('packz: incomplete output retained at ' + str(partial), file=sys.stderr)
        raise
    print(str(target))


def member_path(name):
    p = PurePosixPath(name)
    if p.is_absolute() or '..' in p.parts or '\\' in name or '\x00' in name:
        raise Error('Unsafe archive member path')
    return p


def extract_member(archive, member, root, directories):
    relative = member_path(member.name)
    dest = root.joinpath(*relative.parts)
    for parent in [dest] + list(dest.parents):
        if parent == root: break
        if parent.is_symlink(): raise Error('Archive member traverses a symbolic link')
    if member.isdir():
        dest.mkdir(parents=True, exist_ok=True); directories.append((dest, member)); return
    dest.parent.mkdir(parents=True, exist_ok=True)
    if member.issym():
        link = PurePosixPath(member.linkname)
        if link.is_absolute(): raise Error('Absolute symbolic link refused')
        resolved = (dest.parent / member.linkname).resolve()
        if root != resolved and root not in resolved.parents: raise Error('Escaping symbolic link refused')
        os.symlink(member.linkname, dest)
    elif member.islnk():
        link = root.joinpath(*member_path(member.linkname).parts)
        if not link.is_file() or link.is_symlink() or root not in link.resolve().parents:
            raise Error('Invalid or forward hard link refused')
        os.link(link, dest)
    elif member.isfile():
        with archive.extractfile(member) as inp, dest.open('xb') as out:
            shutil.copyfileobj(inp, out, 65536)
        os.chmod(dest, member.mode & 0o777)
        os.utime(dest, (member.mtime, member.mtime))
    else:
        raise Error('Special device/FIFO archive member refused')


def unpack(args):
    source = regular(args.input)
    if source.name.lower().endswith(ARCHIVES):
        if not args.directory: raise Error('Directory archives require -C <new-directory>')
        root = Path(args.directory).absolute()
        root.mkdir(parents=False, exist_ok=False)
        root = root.resolve()
        marker = root / '.bio-cli-incomplete'
        marker.write_text('Extraction incomplete. Original archive is unchanged.\n')
        directories = []
        with reader(source) as r:
            with tarfile.open(fileobj=r.stream, mode='r|') as archive:
                for member in archive:
                    extract_member(archive, member, root, directories)
            while r.stream.read(65536): pass
        marker.unlink()
        for dest, member in reversed(directories):
            os.chmod(dest, member.mode & 0o777); os.utime(dest, (member.mtime, member.mtime))
        print(str(root))
    else:
        if args.directory: raise Error('-C is for directory archives; use -o for a single file')
        c = compression(source)
        if c not in ('zstd', 'gzip', 'xz', 'bzip2'): raise Error('Unsupported compressed stream')
        suffix = source.suffix.lower()
        if not args.output and suffix not in ('.zst', '.gz', '.bgz', '.bgzip', '.xz', '.bz2'):
            raise Error('Use -o to name the restored file')
        target = Path(args.output).absolute() if args.output else source.with_suffix('')
        if target.exists() or target.is_symlink(): raise Error('Output already exists: ' + str(target))
        fd, name = tempfile.mkstemp(prefix=target.name + '.partial-', dir=str(target.parent))
        partial = Path(name)
        try:
            with os.fdopen(fd, 'wb') as out, reader(source) as r:
                shutil.copyfileobj(r.stream, out, 65536)
                out.flush(); os.fsync(out.fileno())
            publish(partial, target)
        except BaseException:
            print('unpackz: incomplete output retained at ' + str(partial), file=sys.stderr); raise
        print(str(target))


def positive(value):
    n = int(value)
    if n < 1: raise argparse.ArgumentTypeError('must be positive')
    return n


def main():
    invoked = Path(sys.argv[0]).name
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--version', action='version', version='bio-cli ' + VERSION)
    if invoked in ('peek', 'packz', 'unpackz'):
        command = invoked
    else:
        parser.add_argument('command', choices=['peek', 'packz', 'unpackz'])
        command = sys.argv[1] if len(sys.argv) > 1 else ''
    if command == 'peek':
        parser.add_argument('-n', '--lines', type=positive, default=200)
        parser.add_argument('--max-bytes', type=positive, default=LIMIT)
        parser.add_argument('--no-pager', action='store_true')
        parser.add_argument('--header', action='store_true')
        parser.add_argument('--reference')
    elif command == 'packz':
        parser.add_argument('--format', choices=['zstd', 'gzip', 'bgzip'], default='zstd')
        parser.add_argument('-t', '--threads', type=positive, default=2)
        parser.add_argument('-l', '--level', type=int, choices=range(1, 20), default=3)
        parser.add_argument('-o', '--output')
    elif command == 'unpackz':
        parser.add_argument('-C', '--directory')
        parser.add_argument('-o', '--output')
    parser.add_argument('input')
    args = parser.parse_args()
    try:
        {'peek': peek, 'packz': pack, 'unpackz': unpack}[command](args)
        return 0
    except BrokenPipeError:
        sys.stdout = open(os.devnull, 'w'); return 0
    except KeyboardInterrupt:
        print('Interrupted; source data unchanged', file=sys.stderr); return 130
    except (Error, OSError, ValueError, tarfile.TarError, zipfile.BadZipFile, EOFError) as exc:
        print(command + ': ' + str(exc), file=sys.stderr); return 2

if __name__ == '__main__':
    sys.exit(main())
