#!/usr/bin/env python3
"""Portable bounded bioinformatics previews and non-destructive archives."""
import argparse
import contextlib
import gzip
import hashlib
import json
import os
import re
from pathlib import Path, PurePosixPath
import shutil
import signal
import stat
import subprocess
import sys
import tarfile
import tempfile
import zipfile

VERSION = '0.1.6'
LIMIT = 1024 * 1024
INDEX = ('.bai', '.csi', '.tbi', '.gzi', '.0123', '.bwt.2bit.64', '.pac', '.bwt', '.sa')
SPECIAL = ('.bw', '.bigwig', '.bb', '.bigbed', '.h5', '.hdf5', '.h5ad', '.rds', '.rdata', '.rda')
ARCHIVES = ('.tar', '.tar.gz', '.tgz', '.tar.bz2', '.tbz2', '.tar.xz', '.txz', '.tar.zst', '.tzst')
CONTROLS = re.compile(r'[\x00-\x08\x0b-\x1f\x7f-\x9f]')

class Error(Exception):
    pass


def tool(name):
    # Site-local configuration is generated by the installer, never distributed.
    config = Path(__file__).resolve().parent / 'runtime.json'
    mapping = json.loads(config.read_text()) if config.exists() else {}
    result = mapping.get(name) or shutil.which(name)
    if not result or not os.access(result, os.X_OK):
        raise Error('Missing dependency: ' + name + '; install it in a personal environment')
    return result


def regular(value):
    p = Path(value).absolute()
    if not p.is_file():
        raise Error('Not a readable regular file: ' + str(p))
    return p


def compression(path):
    with path.open('rb') as f:
        magic = f.read(6)
    if magic.startswith(b'\x1f\x8b'): return 'gzip'
    if magic.startswith(b'\x28\xb5\x2f\xfd'): return 'zstd'
    if magic.startswith(b'BZh'): return 'bzip2'
    if magic.startswith(b'\xfd7zXZ\x00'): return 'xz'
    return None


class Reader:
    """A bounded consumer; intentional truncation cancels the producer, errors do not."""
    def __init__(self, path, command=None, env=None):
        self.command = command
        if command is None:
            c = compression(path)
            if c:
                command = [tool(c), '-dc', str(path)]
        self.proc = None
        self.truncated = False
        self.error = tempfile.TemporaryFile()
        if command:
            self.proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=self.error, env=env)
            self.stream = self.proc.stdout
        else:
            self.stream = path.open('rb')

    def close(self, cancel=False):
        self.stream.close()
        code = 0
        if self.proc:
            if cancel and self.proc.poll() is None:
                self.proc.terminate()
            try:
                code = self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill(); code = self.proc.wait()
        self.error.seek(0)
        message = self.error.read(8192).decode('utf-8', 'replace').strip()
        self.error.close()
        if code and not cancel:
            raise Error(message or 'Reader failed with exit code ' + str(code))


@contextlib.contextmanager
def reader(path, command=None, env=None):
    r = Reader(path, command, env)
    try:
        yield r
    except BaseException:
        r.close(cancel=True)
        raise
    else:
        r.close(cancel=r.truncated)


def safe_text(data):
    # Escape terminal controls while preserving tabs, newlines and UTF-8.
    text = data.decode('utf-8', 'replace')
    # Scan ordinary text in the regex engine; Python runs only for controls found.
    return CONTROLS.sub(lambda match: '\\x%02x' % ord(match.group()), text)


def preview_stream(r, lines, byte_limit):
    output = bytearray()
    for _ in range(lines):
        remaining = byte_limit - len(output)
        if remaining <= 0:
            r.truncated = True; break
        chunk = r.stream.readline(remaining)
        if not chunk: break
        output.extend(chunk)
    else:
        r.truncated = True
    if len(output) >= byte_limit: r.truncated = True
    if b'\x00' in output:
        return 'Metadata only: binary content detected; use a format-specific reader\n'
    return safe_text(bytes(output))


def display(text, no_pager):
    if sys.stdout.isatty() and not no_pager and shutil.which('less'):
        env = os.environ.copy()
        env['LESSSECURE'] = '1'
        p = subprocess.Popen([shutil.which('less'), '-F', '-S', '-X'], stdin=subprocess.PIPE, env=env)
        try:
            p.communicate(text.encode('utf-8'))
        except BrokenPipeError:
            p.wait()
    else:
        sys.stdout.write(text)


def peek(args):
    path = regular(args.input)
    name = path.name.lower()
    if name.endswith(INDEX + SPECIAL):
        print(safe_text(('Metadata only: %s\nSize: %d bytes\nClass: %s' % (path.name, path.stat().st_size, 'binary index' if name.endswith(INDEX) else 'specialized binary format')).encode('utf-8', 'replace')))
        return
    if name.endswith('.zip'):
        with zipfile.ZipFile(path) as z:
            result = bytearray()
            truncated = False
            for i, member in enumerate(z.infolist()):
                row = ('%d\t%s\n' % (member.file_size, member.filename)).encode()
                if i >= args.lines or len(result) + len(row) > args.max_bytes:
                    truncated = True; break
                result.extend(row)
        display(safe_text(result), args.no_pager)
    elif name.endswith(ARCHIVES):
        result = bytearray(); truncated = False
        with reader(path) as r:
            with tarfile.open(fileobj=r.stream, mode='r|') as archive:
                for i, member in enumerate(archive):
                    row = ('%d\t%s\n' % (member.size, member.name)).encode()
                    if i >= args.lines or len(result) + len(row) > args.max_bytes:
                        r.truncated = truncated = True; break
                    result.extend(row)
                    # Asking for the next header skips the current member's payload.
                    # Stop now, before a large FASTQ/BAM is read just to discover N+1.
                    if i + 1 >= args.lines or len(result) >= args.max_bytes:
                        r.truncated = truncated = True; break
            # tar end markers can precede a compressed checksum; drain to verify it.
            if not r.truncated:
                while r.stream.read(65536): pass
        display(safe_text(result), args.no_pager)
    else:
        command = None
        env = None
        if name.endswith(('.bam', '.cram')):
            command = [tool('samtools'), 'view', '--no-PG', '-H' if args.header else '-h']
            if name.endswith('.cram') and not args.header:
                if not args.reference:
                    raise Error('CRAM record preview requires --reference <local.fa>; use --header for header only')
                reference = regular(args.reference)
                if not Path(str(reference) + '.fai').is_file():
                    raise Error('Reference .fai must already exist; peek never creates an index')
                command += ['-T', str(reference)]
                env = os.environ.copy(); env['REF_PATH'] = str(reference.parent); env['REF_CACHE'] = ''
            command.append(str(path))
        elif name.endswith('.bcf'):
            command = [tool('bcftools'), 'view', '--no-version', '-h' if args.header else '-Ov', str(path)]
        elif args.header:
            raise Error('--header is supported for BAM, CRAM and BCF; use -n for text formats')
        with reader(path, command, env) as r:
            text = preview_stream(r, args.lines, args.max_bytes)
            truncated = r.truncated
        display(text, args.no_pager)
    if truncated:
        print('peek: preview limit reached; this is not a complete integrity check', file=sys.stderr)


def compressor(fmt, threads, level):
    if fmt == 'zstd': return [tool('zstd'), '-q', '-c', '-T' + str(threads), '-' + str(level)]
    if fmt == 'gzip': return [tool('gzip'), '-c', '-n', '-' + str(min(level, 9))]
    return [tool('bgzip'), '-c', '-@', str(threads), '-l', str(min(level, 9))]


def publish(partial, target):
    # Atomic no-clobber publication on the same filesystem.
    os.link(str(partial), str(target))
    partial.unlink()


def validate_pack_tree(source):
    """Reject members our safe restore cannot reproduce; never follow links."""
    root = source.resolve()
    member_path(source.name)
    if source.name == '.bio-cli-incomplete':
        raise Error('Source name conflicts with the restore status marker')
    def check(path):
        member_path(str(path.relative_to(source)))
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            value = os.readlink(path)
            if os.path.isabs(value):
                raise Error('Directory contains an absolute symbolic link: ' + str(path))
            target = (path.parent / value).resolve()
            if target != root and root not in target.parents:
                raise Error('Directory contains an escaping symbolic link: ' + str(path))
        elif not (stat.S_ISREG(mode) or stat.S_ISDIR(mode)):
            raise Error('Directory contains an unsupported special member: ' + str(path))
    def fail(exc):
        raise exc
    for parent, directories, files in os.walk(source, followlinks=False, onerror=fail):
        for name in directories + files:
            check(Path(parent) / name)


def pack(args):
    source = Path(args.input).absolute()
    if source.is_symlink() or not (source.is_file() or source.is_dir()):
        raise Error('Input must be a regular file or directory, not a top-level symbolic link')
    is_dir = source.is_dir()
    if is_dir and args.format != 'zstd':
        raise Error('Directory archives use zstd (.tar.zst) in this version')
    suffix = '.tar.zst' if is_dir else '.zst' if args.format == 'zstd' else '.gz'
    target = Path(args.output).absolute() if args.output else source.with_name(source.name + suffix)
    if target.exists() or target.is_symlink(): raise Error('Output already exists: ' + str(target))
    if not target.parent.is_dir(): raise Error('Output parent directory does not exist')
    if is_dir and (target.parent.resolve() == source.resolve() or source.resolve() in target.parent.resolve().parents):
        raise Error('Archive output must be outside the source directory')
    if not is_dir and source.name.lower().endswith(('.gz', '.zst', '.xz', '.bz2', '.bam', '.cram', '.bcf', '.zip')):
        print('packz: input is already compressed; additional compression may save little space', file=sys.stderr)
    if is_dir:
        validate_pack_tree(source)
    command = compressor(args.format, args.threads, args.level)
    fd, name = tempfile.mkstemp(prefix=target.name + '.partial-', dir=str(target.parent))
    partial = Path(name)
    try:
        with os.fdopen(fd, 'wb') as out:
            if is_dir:
                env = os.environ.copy(); env['COPYFILE_DISABLE'] = '1'
                tar = subprocess.Popen([tool('tar'), '-cf', '-', '-C', str(source.parent), '--', source.name], stdout=subprocess.PIPE, env=env)
                try:
                    result = subprocess.run(command, stdin=tar.stdout, stdout=out)
                    tar.stdout.close()
                    tarcode = tar.wait()
                finally:
                    if tar.poll() is None: tar.terminate(); tar.wait()
                if result.returncode or tarcode: raise Error('Archive/compressor failed; partial output retained')
            else:
                before = source.stat()
                with source.open('rb') as inp:
                    result = subprocess.run(command, stdin=inp, stdout=out)
                after = source.stat()
                if result.returncode: raise Error('Compressor failed; partial output retained')
                if (before.st_size, before.st_mtime_ns, before.st_ino) != (after.st_size, after.st_mtime_ns, after.st_ino):
                    raise Error('Source changed during compression; partial output retained')
            out.flush(); os.fsync(out.fileno())
        check = [tool('zstd' if args.format == 'zstd' else 'gzip'), '-t', str(partial)]
        if subprocess.run(check).returncode: raise Error('Compressed stream integrity test failed')
        publish(partial, target)
    except BaseException:
        print('packz: incomplete output retained at ' + str(partial), file=sys.stderr)
        raise
    print(str(target))


def member_path(name):
    p = PurePosixPath(name)
    if p.is_absolute() or '..' in p.parts or '\\' in name or '\x00' in name:
        raise Error('Unsafe archive member path')
    return p


def extract_member(archive, member, root, directories):
    relative = member_path(member.name)
    dest = root.joinpath(*relative.parts)
    for parent in [dest] + list(dest.parents):
        if parent == root: break
        if parent.is_symlink(): raise Error('Archive member traverses a symbolic link')
    if member.isdir():
        dest.mkdir(parents=True, exist_ok=True); directories.append((dest, member)); return
    dest.parent.mkdir(parents=True, exist_ok=True)
    if member.issym():
        link = PurePosixPath(member.linkname)
        if link.is_absolute(): raise Error('Absolute symbolic link refused')
        resolved = (dest.parent / member.linkname).resolve()
        if root != resolved and root not in resolved.parents: raise Error('Escaping symbolic link refused')
        os.symlink(member.linkname, dest)
    elif member.islnk():
        link = root.joinpath(*member_path(member.linkname).parts)
        if not link.is_file() or link.is_symlink() or root not in link.resolve().parents:
            raise Error('Invalid or forward hard link refused')
        os.link(link, dest)
    elif member.isfile():
        with archive.extractfile(member) as inp, dest.open('xb') as out:
            shutil.copyfileobj(inp, out, 65536)
        os.chmod(dest, member.mode & 0o777)
        os.utime(dest, (member.mtime, member.mtime))
    else:
        raise Error('Special device/FIFO archive member refused')


def unpack(args):
    source = regular(args.input)
    if args.directory or (not args.output and source.name.lower().endswith(ARCHIVES)):
        if not args.directory: raise Error('Directory archives require -C <new-directory>')
        root = Path(args.directory).absolute()
        status = root.with_name(root.name + '.bio-cli-incomplete')
        # A sibling marker remains writable even if archive metadata makes root read-only.
        with status.open('x') as out:
            out.write('Extraction incomplete. Original archive is unchanged.\n')
        try:
            root.mkdir(parents=False, exist_ok=False)
        except BaseException:
            status.unlink()
            raise
        root = root.resolve()
        marker = root / '.bio-cli-incomplete'
        directories = []
        try:
            marker.write_text('Extraction incomplete; see sibling status marker.\n')
            with reader(source) as r:
                with tarfile.open(fileobj=r.stream, mode='r|') as archive:
                    for member in archive:
                        if member_path(member.name) == PurePosixPath('.bio-cli-incomplete'):
                            raise Error('Archive member conflicts with restore status marker')
                        extract_member(archive, member, root, directories)
                while r.stream.read(65536): pass
            marker.unlink()
            for dest, member in reversed(directories):
                os.chmod(dest, member.mode & 0o777)
                os.utime(dest, (member.mtime, member.mtime))
            status.unlink()
        except BaseException:
            # Best effort compatibility marker; sibling status is authoritative.
            try:
                with marker.open('x') as out:
                    out.write('Extraction incomplete; see sibling status marker.\n')
            except OSError:
                pass
            print('unpackz: incomplete restore; status at ' + str(status), file=sys.stderr)
            raise
        print(str(root))
    else:
        if args.directory: raise Error('-C is for directory archives; use -o for a single file')
        c = compression(source)
        if c not in ('zstd', 'gzip', 'xz', 'bzip2'): raise Error('Unsupported compressed stream')
        suffix = source.suffix.lower()
        if not args.output and suffix not in ('.zst', '.gz', '.bgz', '.bgzip', '.xz', '.bz2'):
            raise Error('Use -o to name the restored file')
        target = Path(args.output).absolute() if args.output else source.with_suffix('')
        if target.exists() or target.is_symlink(): raise Error('Output already exists: ' + str(target))
        fd, name = tempfile.mkstemp(prefix=target.name + '.partial-', dir=str(target.parent))
        partial = Path(name)
        try:
            with os.fdopen(fd, 'wb') as out, reader(source) as r:
                shutil.copyfileobj(r.stream, out, 65536)
                out.flush(); os.fsync(out.fileno())
            publish(partial, target)
        except BaseException:
            print('unpackz: incomplete output retained at ' + str(partial), file=sys.stderr); raise
        print(str(target))


def positive(value):
    n = int(value)
    if n < 1: raise argparse.ArgumentTypeError('must be positive')
    return n


PEEK_EXAMPLES = """常用示例（文件名均为示例，请替换为自己的文件）：
  peek annotation.gff3.gz                 查看压缩的 GFF3 注释
  peek -n 30 reference.fa.gz              查看 FASTA 的前 30 行
  peek -n 20 reads.fastq.gz               查看 FASTQ 的前 20 行
  peek -n 50 variants.vcf.gz              查看 VCF 开头，包含元信息和表头
  peek reference.fa.fai                   查看参考序列的文本索引
  peek reference.fa.bwt.2bit.64           二进制索引只显示元数据
  peek --header alignments.bam           只看 BAM 头部
  peek -n 50 alignments.bam               查看 BAM 头部及后续比对记录
  peek variants.bcf                      将 BCF 转成 VCF 文本预览
  peek --header alignments.cram          只看 CRAM 头部，不需要参考文件
  peek --reference reference.fa alignments.cram
                                        用本地参考预览 CRAM（需已有 .fai）
  peek -n 10 archive.tar.zst              列出归档前 10 个成员，不解包
  peek --max-bytes 65536 large.tsv.zst    最多读取 64 KiB 预览内容
  peek --no-pager annotation.gtf.gz      直接输出，不进入分页器
  peek --no-pager table.tsv | head -10   将预览结果交给其他命令
  peek "sample notes.tsv"                含空格的文件名加引号
  peek -- -sample.fa                     以短横线开头的文件名先加 --

格式与边界：
  文本：FASTA/FASTQ、GFF/GFF3/GTF、BED/WIG、VCF/gVCF、SAM、TSV/CSV、
        MTX、FAI/DICT、文本 ANN/AMB；支持 gzip/BGZF、zstd、xz、bzip2。
  BAM/CRAM 依赖 samtools，BCF 依赖 bcftools；归档支持 tar 变体和 ZIP。
  BAI/CSI/TBI/GZI、BWA/BWA-MEM2 二进制索引仅显示元数据；
  BigWig/BigBed、HDF5/H5AD、RDS/RData 仅标识类别，不展开对象。
  默认上限为 200 行或 1 MiB，先达到者为准；长行可能被截断。
  -n 是物理行数，不是序列、read 或变异数；FASTQ 20 行仅在标准四行格式
  且未触及字节上限时对应 5 条记录。BAM/VCF 的头部也占用行数。
  归档中 -n 是成员数，--max-bytes 限制列表输出；寻找后续成员仍需扫描。
  预览不会修改源文件或自动建索引，也不能代替全文件完整性检查。
  分页器内按 q 退出，/ 搜索，空格翻页；管道输出自动禁用分页。
"""


def configure_command(parser, command):
    parser.formatter_class = argparse.RawDescriptionHelpFormatter
    parser.description = {
        'peek': '快速、限量预览生信文件：无需先将压缩文本解压到磁盘。',
        'packz': '压缩文件或打包目录；保留源文件，拒绝覆盖已有输出。',
        'unpackz': '恢复压缩文件或 tar 归档；目标必须是新文件或新目录。',
    }[command]
    parser.add_argument('--version', action='version', version='bio-cli ' + VERSION)
    if command == 'peek':
        parser.add_argument('-n', '--lines', type=positive, default=200, metavar='N', help='最多预览 N 行；归档为 N 个成员（默认：200）')
        parser.add_argument('--max-bytes', type=positive, default=LIMIT, metavar='BYTES', help='预览字节上限，填写正整数（默认：1048576，即 1 MiB）')
        parser.add_argument('--no-pager', action='store_true', help='直接输出到终端；用于重定向或管道时可显式指定')
        parser.add_argument('--header', action='store_true', help='仅显示 BAM/CRAM/BCF 头部，仍受行数和字节上限限制')
        parser.add_argument('--reference', metavar='FASTA', help='CRAM 记录预览所需的本地参考；必须已有 FASTA.fai')
        parser.epilog = PEEK_EXAMPLES
    elif command == 'packz':
        parser.add_argument('--format', choices=['zstd', 'gzip', 'bgzip'], default='zstd', help='压缩格式（默认：zstd）；目录只支持 zstd')
        parser.add_argument('-t', '--threads', type=positive, default=2, help='工作线程数（默认：2；gzip 始终单线程）')
        parser.add_argument('-l', '--level', type=int, choices=range(1, 20), default=3, help='压缩级别（默认：3）；gzip/BGZF 高于 9 时按 9 使用')
        parser.add_argument('-o', '--output', help='指定新输出文件；默认在源文件旁添加 .zst/.gz 或 .tar.zst')
        parser.epilog = '示例：\n  packz table.tsv\n  packz project_directory\n  packz --format bgzip variants.vcf\n  packz -t 2 -l 6 -o archive.tar.zst project_directory'
    elif command == 'unpackz':
        mode = parser.add_mutually_exclusive_group()
        mode.add_argument('-C', '--directory', help='按 tar 归档恢复到新目录；显式指定时不依赖文件后缀')
        mode.add_argument('-o', '--output', help='按单个压缩流恢复到新文件；即使名字含 .tar 也不展开归档')
        parser.epilog = '示例：\n  unpackz table.tsv.zst -o restored.tsv\n  unpackz archive.tar.zst -C restored_project\n\nZIP 仅支持 peek 列表预览，不支持 unpackz 解包。'
    parser.add_argument('input', metavar='FILE' if command != 'packz' else 'PATH', help='待处理的文件' if command != 'packz' else '待压缩的文件或目录')


TOOL_GUIDE = [
    ('peek', '限量预览生信文件', 'peek -n 20 annotation.gff3.gz'),
    ('packz', '压缩文件或目录', 'packz project_directory'),
    ('unpackz', '恢复到新文件或目录', 'unpackz archive.tar.zst -C restored'),
    ('rg', '搜索文本内容', "rg -n 'ERROR|failed' logs/"),
    ('fd', '按文件名寻找文件', 'fd -t f -e bam .'),
    ('eza', '文件列表和目录树', 'eza --tree --level=2 reference/'),
    ('dua', '统计目录磁盘占用', 'dua aggregate results/ reference/'),
    ('gdu', '交互查看目录占用', 'gdu results/'),
    ('dust-du', '显示目录占用分布', 'dust-du results/'),
    ('bat', '查看文本及语法高亮', 'bat script.py'),
    ('zstd', '原生 zstd 压缩与校验', 'zstd -t archive.tar.zst'),
    ('samtools', '比对格式工具', 'samtools view -H alignments.bam'),
    ('bcftools', '变异格式工具', 'bcftools view -h variants.bcf'),
    ('bgzip', 'BGZF 分块压缩', 'bgzip -c variants.vcf > variants.vcf.gz'),
]


def tools_overview(args):
    print('bio-cli 工具总览（示例名请替换为自己的文件）')
    for name, purpose, example in TOOL_GUIDE:
        print('%-10s %s\n           %s' % (name, purpose, example))
    print('\n各工具是独立命令；使用 NAME --help 查看完整参数。')
    print('bio-cli doctor 检查实际路径和版本；不会安装、修改配置或扫描数据目录。')
    print('peek 只预览部分内容；rg 搜索预览结果不能代表全文件。')


def doctor(args):
    rows = []
    for name in ['python3', 'tar', 'gzip', 'bzip2', 'xz'] + [x[0] for x in TOOL_GUIDE[3:]]:
        row = {'tool': name, 'path': None, 'status': 'ERROR'}
        try:
            path = tool(name)
            row['path'] = path
            with tempfile.TemporaryFile() as output:
                proc = subprocess.run([path, '--version'], stdin=subprocess.DEVNULL,
                                      stdout=output, stderr=subprocess.STDOUT, timeout=15)
                output.seek(0)
                row['version'] = safe_text(output.read(2048)).strip().splitlines()[:3]
            row['status'] = 'OK' if proc.returncode == 0 else 'ERROR'
            row['exit_code'] = proc.returncode
        except (Error, OSError, ValueError, subprocess.TimeoutExpired) as exc:
            row['error'] = str(exc)
        rows.append(row)
    result = {'bio_cli_version': VERSION, 'checks': rows,
              'scope': 'Path and version probes only; not full format capability validation'}
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print('bio-cli ' + VERSION + '：只读路径与版本检查')
        for row in rows:
            print(safe_text(('%s %s %s\n  %s' % (row['status'], row['tool'], row['path'] or '-',
                  '; '.join(row.get('version', [])) or row.get('error', ''))).encode('utf-8', 'replace')))
        print('检查不等于完整格式能力验收；输出含本机路径，分享前请检查。')
    if any(row['status'] != 'OK' for row in rows):
        raise Error('One or more dependency checks failed')


def main():
    invoked = Path(sys.argv[0]).name
    commands = ('peek', 'packz', 'unpackz')
    if invoked in commands:
        parser = argparse.ArgumentParser(prog=invoked)
        configure_command(parser, invoked)
    else:
        parser = argparse.ArgumentParser(prog='bio-cli', description='生信文件预览、压缩与恢复工具；各命令使用 --help 查看示例。')
        parser.add_argument('--version', action='version', version='bio-cli ' + VERSION)
        subparsers = parser.add_subparsers(dest='command', required=True)
        for name in commands:
            configure_command(subparsers.add_parser(name, prog=name), name)
        subparsers.add_parser('tools', help='工具用途和常用示例')
        doctor_parser = subparsers.add_parser('doctor', help='只读检查工具路径与版本，不修改环境')
        doctor_parser.add_argument('--json', action='store_true', help='输出本机诊断 JSON；含实际路径，请勿直接公开')
    args = parser.parse_args()
    command = invoked if invoked in commands else args.command
    try:
        {'peek': peek, 'packz': pack, 'unpackz': unpack, 'tools': tools_overview, 'doctor': doctor}[command](args)
        return 0
    except BrokenPipeError:
        sys.stdout = open(os.devnull, 'w'); return 0
    except KeyboardInterrupt:
        print('Interrupted; source data unchanged', file=sys.stderr); return 130
    except (Error, OSError, ValueError, tarfile.TarError, zipfile.BadZipFile, EOFError, OverflowError, RuntimeError) as exc:
        print(safe_text((command + ': ' + str(exc)).encode('utf-8', 'replace')), file=sys.stderr); return 2

if __name__ == '__main__':
    sys.exit(main())
